### ISSUE TITLE
Add option to enable testnet

### ISSUE THREAD

**Issue by fnando** [Block-Equity/stellar-ios-wallet#110]
# I'm submitting a...

- [ ] Bug report  
- [x] Feature request  
- [ ] ~~Support request / code question~~

# New Feature

Add option under `Settings > Development` to enable testnet. The app is so nice that I wish I could use it while I'm developing to Stelalr env as well.

### Please detailed description of how you propose the feature could work:

With this option enabled, requests would switch from `https://horizon.stellar.org` to `https://horizon-testnet.stellar.org`.

**Comment by ndizazzo** [comment]
Hey @fnando - I like this idea! There’s often times I’m working on the app and want to switch to do some testing on a testnet as well... I’ll add this to our list of “nice to haves”.

**Comment by fnando** [comment]
I only tried the App Store release. 

What about adding an option under iPhone's Settings > BlockEQ > Advanced > Enable Development Mode (this view can have some additional information about why this exists).

One suggestion for this: instead of just enabling/disabling testnet, make it an input that defaults to Stellar's horizon testnet, but enabling any horizon instance to be used.

**Comment by ndizazzo** [comment]
This issue is addressed by #232 and should be in the next release. I've backlogged a task to allow for custom horizon servers - I need to do some refactoring first. 

Thanks @fnando!

**Comment by fnando** [comment]
@ndizazzo thanks a lot for this! 🎉
