### ISSUE TITLE
New Settings + Drop Down Coin Selection

### ISSUE THREAD

**Issue by satbam** [Block-Equity/stellar-ios-wallet#30]
This bounty pays out 10,000,000 PTS.

We require 2 items to be completed to award the bounty.

1. A settings view controller with a grouped tableview to replace the current action sheet in the main wallet view controller.

2. A token selection view controller that is initiated by selecting the title of the main wallet view controller in the navigation bar. Currently the token selection is done by selecting the menu bar however as we are adding new features to the menu bar we have decided to remove token selection from it. 

Once you have completed the task please submit a pull request. If the bounty offered label is not displayed anymore it means that someone has taken up this offer. 

If you have taken up the offer and we do not receive a pull request in 5 days we will have to open up the bounty offer again.

**Comment by ndizazzo** [comment]
@satbam I'd love to tackle this!

**Comment by satbam** [comment]
Awesome @ndizazzo looking forward.

**Comment by ndizazzo** [comment]
I think this can be closed now 👍
