### ISSUE TITLE
Convert application navigation to tabbar.

### ISSUE THREAD

**Issue by satbam** [Block-Equity/stellar-ios-wallet#35]
This bounty pays out 5,000,000 PTS.

We require 2 items to be completed to award the bounty.

1. Remove all the side menu and add a tab bar controller with 4 sections. Assets, Trading, Receive(QR Code), Settings

2. On the Main wallets view, move the send icon to the top right and wallets (where you choose) your token to the top left of the navigation menu and is now presented modally rather than via the side menu.

**Comment by ndizazzo** [comment]
I can tackle this over the weekend.

I'll take this one too 🙃

**Comment by satbam** [comment]
Awesome @ndizazzo !
