### ISSUE TITLE
Pin View Redesign

### ISSUE THREAD

**Issue by satbam** [Block-Equity/stellar-ios-wallet#37]
This bounty rewards 6M Blockpoints.

Our current pin view is in need of major love.

1. Remove the confirmation button and add a custom keyboard like the send screen.
2. Present and dismiss it beautifully with both light and dark modes.
3. Add an option to enable and disable it within settings and for 3 scenerios - during launch, for sending payments, when trading. Viewing mnemonic  should always require a passcode.
4. Use Coinbase as an inspiration.

**Comment by ndizazzo** [comment]
... I'll take it... again :)

**Comment by ndizazzo** [comment]
I think that does it for this bounty, when #43 gets accepted!
