### ISSUE TITLE
Remove option of 'Remove Asset' when balance is more than 0

### ISSUE THREAD

**Issue by MeghaBambra** [Block-Equity/stellar-ios-wallet#57]
* This is on the asset list view

**Comment by JonLister** [comment]
Definitely agree button should be removed or hidden unless balance is 0

![image from ios 1](https://user-images.githubusercontent.com/36420363/44821818-9ca89100-abc5-11e8-9c25-b65eb5fcedaa.jpg)

**Comment by ndizazzo** [comment]
This is addressed with #96
