### ISSUE TITLE
[BUG] Rounding error display

### ISSUE THREAD

**Issue by JonLister** [Block-Equity/stellar-ios-wallet#78]
While emptying a wallet, balance is rounded. 
See below 8 XLM is available, rounded up from 7.9999 XLM
Not clear for users trying to send 100% of their available balance

![image from ios 6](https://user-images.githubusercontent.com/36420363/45122035-bcddd000-b130-11e8-98a2-0d30c45fc091.png)

**Comment by ndizazzo** [comment]
This issue is addressed by PR #130 which corrects this behaviour. It now shows the unrounded amount available across both send view controllers.
