### ISSUE TITLE
[BUG] Application crash after sending Lumens

### ISSUE THREAD

**Issue by ndizazzo** [Block-Equity/stellar-ios-wallet#80]
## Priority
Normal

## Observed Behaviour
The application crashed after successfully sending (transaction was submitted to the Stellar network) Lumens to a recipient address.

## Expected Behaviour
After sending Lumens, the application should navigate back to the main wallet interface, with a new row in the transaction log reflecting the amount sent.

## Reproduction Steps
1. Navigate to “send”
2. Scan QR code
3. Enter Lumen amount
4. Hit “send”
5. Wait for activity indicator
6. Observe crash occurs

**Comment by satbam** [comment]
Fixed
