### ISSUE TITLE
Importing wallet from seed

### ISSUE THREAD

**Issue by fnando** [Block-Equity/stellar-ios-wallet#83]
Any chance I can import a wallet from a seed? I know one shouldn't be doing this, but I have a vanity address for small transactions and I'd like to import it into BlockEQ.

**Comment by ndizazzo** [comment]
Hey @fnando 

You can definitely import a wallet using a seed phrase. 

If you already have a wallet on the iOS app, you can navigate to “Settings > Clear Wallet” and follow the prompts. Before you do that though, I highly recommend you triple check that you’ve recorded your existing mnemonic.

After that’s done, you will be kicked back to the intro screen with two buttons, “create new wallet” and “recover wallet”. The second option will allow you to paste your mnemonic for the vanity address into the app.
