### ISSUE TITLE
[BUG] 100% Trade button leaving residual amount (rounding issue)

### ISSUE THREAD

**Issue by JonLister** [Block-Equity/stellar-ios-wallet#91]
# I'm submitting a...
[X] Bug report  
[ ] Feature request  
[ ] ~~Support request / code question~~

# Bug
### What is the expected behavior?

100% trade of any Stellar token should leave no residual balance
Should be able to remove any asset after a 100% trade

### What is the current behavior?

100% trade can leave a residual amount from rounding
Error message displayed after attempting to remove the asset (balance displays 0.00)

### Please provide steps to reproduce the issue
**_Screenshots and videos also help, where possible! Be mindful of sensitive data._**

1. Perform a 100% trade with a fractional amount 6-7 decimal places
2. Attempt to remove the asset

![img_0009](https://user-images.githubusercontent.com/36420363/46175549-5c970580-c27a-11e8-8332-015ae623e148.JPG)

**Comment by ndizazzo** [comment]
I think this is universally an issue across transactions with Lumens (trade / send). 

The the available amount doesn't incorporate network fees. This has the effect of allowing the user to send more than allowed by the exact amount of the fee, which ultimately causes the transaction to also fail.

**Comment by ndizazzo** [comment]
This bug is now addressed by changes in #201, and should no longer leave residual amounts.
